name: Export to HTML5 and deploy to GitHub Pages
on:
  push:
    branches: [ master ]

env:
  GODOT_VERSION: 3.3
  EXPORT_NAME: Jottery

jobs:
  export-html5:
    name: Export to HTML5 and deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Export to HTML5
        run: godot -v --export "HTML5" ./build/web/index.html

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync 📚
        run: |
          apt-get update -qq && apt-get install -qqq rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: build/web
          # Artifacts are large; don't keep the branch's history.
          SINGLE_COMMIT: true